config/routes.rb
require 'sidekiq/web'
require 'sidekiq/cron/web'

Rails.application.routes.draw do
  mount Sidekiq::Web, at: '/sidekiq'
  mount SuperfeedrEngine::Engine => SuperfeedrEngine::Engine.base_path # Use the same to set path in the engine initialization!

  namespace :admin do
    devise_scope :admin_user do
      get '/stats/:scope' => "stats#stats", as: :admin_stats
    end
  end

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users, class_name: 'FormUser', :controllers => { omniauth_callbacks: 'omniauth_callbacks', registrations: 'registrations', sessions: 'sessions', invitations: 'invitations' }, :skip => [:sessions]
  as :user do
    get 'login' => 'devise/sessions#new', :as => :new_user_session
    post 'login' => 'devise/sessions#create', :as => :user_session
    delete 'logout' => 'devise/sessions#destroy', :as => :destroy_user_session
  end
  root 'onboarding#check'
  get '/setup' => 'setup#index'

  get '/welcome' => 'onboarding#step1'
  get '/welcome/step0' => 'onboarding#step1'
  get '/welcome/step1' => 'onboarding#step1'
  get '/welcome/step1/done' => 'onboarding#step1_done'
  get '/welcome/step2' => 'onboarding#step2'
  get '/welcome/step3' => 'onboarding#step3'
  post '/welcome/step3/publish' => 'onboarding#step3_publish', as: 'onboarding_schedule_post'
  get '/welcome/step4' => 'onboarding#step4'
  get '/welcome/step5' => 'onboarding#step5'
  get '/welcome/step6' => 'onboarding#step6'

  resources :schedules, only: :index do
    post '/add_timeslot' => 'schedules#add_timeslot'
  end
  resources :categories do
    resources :posts, only: [:create]
    post 'reorder'
    get '/posts/bulk' => 'posts#show_bulk'
    post '/posts/preview' => 'posts#bulk_preview'
    post '/posts/bulk' => 'posts#create_bulk'
  end
  resources :feeds, only: [:index, :create, :update, :destroy]
  resources :identities, path: 'accounts'
  resources :posts, only: [:update, :edit, :destroy, :create]
  resources :timeslots, only: [:new, :create, :edit, :destroy]
  resources :assets, path: 'files', only: [:create, :destroy]

  get '/import/twitter' => 'import#twitter_setup'
  post '/import/twitter' => 'import#twitter'
  get '/import/twitter/:id' => 'import#show_twitter', as: 'import_show_twitter'
  post '/import' => 'import#import'
  get '/import/csv' => 'import#csv_setup'
  post '/import/csv' => 'import#csv_import'
  post '/import/csv/preview' => 'import#csv_preview'

  get '/library' => 'library#index'
  get '/add_content' => 'library#add_content', as: 'add_content'

  get '/queue' => 'queue#index'
  get '/queue/reschedule' => 'queue#reschedule'
  post '/queue/skip/:update_id' => 'queue#skip', as: 'skip_update'
  get '/analytics' => 'analytics#index'

  get '/:id' => "shortener/shortened_urls#show", constraints: { subdomain: 'shorten' }

  post '/ajax/scraper' => 'ajax#scraper'

end

app/models/schedule.rb
class Schedule < ActiveRecord::Base
  belongs_to :identity
  belongs_to :user
  has_many :timeslots, dependent: :destroy
  has_many :updates, through: :timeslots

  def timeslots_on day
    self.timeslots.where day: day
  end

  def remove_scheduled_updates
    updates.scheduled.order(scheduled_at: :desc).each { |u| u.unschedule }
  end

  def number_of_unique_days
    return -1 if timeslots.count == 0
    timeslots.map(&:category).map(&:number_of_unique_days).uniq.min
  rescue
    return -1
  end

end

app/controllers/schedules_controller.rb
class SchedulesController < ApplicationController
  skip_before_filter :onboarding, only: :add_timeslot

  def index
    @timeslots = current_user.timeslots.filter(filtering_params)
    @identities = current_user.identities
    @new_timeslot = Timeslot.new
  end

  def add_timeslot
    offset = Time.zone.parse(timeslot_params[:offset].sub('.',':'))
    @timeslot = Timeslot.create timeslot_params.merge offset: (offset.hour * 60 + offset.min)

    QueueWorker.perform_async(@timeslot.category.id)

    respond_to do |format|
      format.html { redirect_to schedules_path }
      format.js
    end
  end

  def reschedule
    @schedule = Schedule.find params[:schedule_id]
    @schedule.reschedule
  end

  private

  def timeslot_params
    params.require(:timeslot).permit(:schedule_id, :day, :offset, :category_id, identity_ids: [])
  end

  def filtering_params
    params.slice :identities
  end


end

app/helpers/schedules_helper.rb
module SchedulesHelper

  def day_options
    days = Date::DAYNAMES.each_with_index.map { |d,i| [d, i] }
    sunday = days.shift
    days << sunday
  end

  def category_options
    current_user.categories.map { |l| ["#{l.name} (#{l.posts.count})", l.id] }
  end

  def identity_options
    current_user.identities.map do |i|
      ["#{i.subname} - #{i.provider}", i.id]
    end
  end

  def block_time block, format
    offset = block * minutes_per_block
    offset_to_time offset, format
  end

  def offset_to_time offset, format
    time = Time.zone.now.change({ hour: offset / 60, min: offset % 60 }) # offset is in minutes!
    time.strftime(format)
  end

  def minute_blocks_per_day
    24*60/minutes_per_block
  end

  # this will take a schedule and group the timeslots per day and then by timeblock (ie. per 30 minute interval)
  def convert_to_timeblocks timeslots
    slots = timeslots.order(:offset).group_by(&:day)
    Hash[slots.map { |i,slots| [i, slots.group_by { |slot| slot.offset / minutes_per_block }]}]
  end

  def minutes_per_block
    120
  end

end

app/views/schedules/_add_timeslot.html.haml
= form_for timeslot, url: schedule_add_timeslot_url(schedule), remote: true, html: { class: 'form-horizontal', id: "#{defined? id ? id : 'add_timeslot'}" } do |f|
  = f.hidden_field :schedule_id, value: schedule.id
  .form-group
    = f.label :day, class: 'col-sm-2 control-label'
    .col-sm-10
      = f.select :day, day_options, { selected: (defined?(day) ? day : 0).to_s }, { class: 'form-control' }
  .form-group
    = f.label :offset, 'Time', class: 'col-sm-2 control-label', required: 'required'
    .col-sm-10
      = f.text_field :offset, placeholder: "Type scheduling time, eg. 2:32pm or 14:32", class: 'form-control'
  .form-group
    = f.label :category_id, 'Category', class: 'col-sm-2 control-label'
    .col-sm-10
      = f.select :category_id, category_options, {}, { class: 'form-control' }
  .form-group
    .col-sm-10.col-sm-offset-2
      = f.submit "Add timeslot", class: 'btn btn-primary', data: { disable_with: 'Submitting...' }

app/views/schedules/_schedule.html.haml
.pull-right
  = form_tag schedules_path, method: 'GET' do
    .text-muted.small.m10
      filter by account:
      - identities.each_with_index do |identity, index|
        .account-picker-item.includes-provider-logo{data: {toggle: 'tooltip', title: "#{identity.subname}"}}
          = check_box_tag '', identity.id, false, id: "filter_identity_#{index}", class: 'filter-identity'
          = label_tag "filter_identity_#{index}", class: 'm0' do
            = image_tag identity.image
            %i.fa{class: "fa-#{identity.provider} bg-#{identity.provider} provider-logo-br logo-square logo-radius text-center"}
%table.calendar.schedule
  %thead
    %tr
      %th
      - 0.upto(6).each do |day|
        %th
          = Date::DAYNAMES[day]
  %tbody
    - timeblocks = convert_to_timeblocks(timeslots)
    - minute_blocks_per_day.times.each do |block|
      %tr
        %td
          = block_time(block, "%-I %P")
        - 7.times.each do |day|
          %td.timeslot-holder{id: "day_#{day}_block_#{block}"}
            - ((timeblocks[day] || {})[block] || []).each do |slot|
              = render partial: 'schedules/timeslot', locals: { slot: slot }
            %a.add-timeslot.hide.x-small.text-center{:href => "!#", data: {day: day, time: block_time(block, "%H:%M"), toggle: 'modal', target: "#dialog_timeslot"}}
              %i.fa.fa-plus
              add timeslot
  %tfooter
    %tr
      %td
      - 0.upto(6).each do |day|
        %td.center
          %a.btn.btn-default.btn-sm.add-timeslot.center{'data-day': day, 'data-toggle': 'modal', 'data-target': "#dialog_timeslot"}
            Add timeslot


.modal.fade{tabindex: 1, role: 'dialog', 'aria-hidden': "true", id: "dialog_timeslot", 'data-show': 'false'}
  .modal-dialog
    .modal-content
      .modal-header
        %button.close{type: 'button', 'aria-label': 'Close', 'data-dismiss': 'modal'}
          %span{'aria-hidden': true}
            &times;
        .modal-title.large
          Add a new timeslot
      .modal-body
        = render partial: 'timeslots/form', locals: { timeslot: Timeslot.new, id: "dialog_timeslot" }


- content_for :javascripts do
  :coffeescript
    $ ->
      $('.filter-identity').change ->
        $(".timeslot").hide()
        ids = $('.filter-identity:checked').map ->
          $(this).val()
        if ids.length == 0
          timeslots_with_identity().show()
        else
          $.each ids, ->
            timeslots_with_identity(this).show()

    window.timeslots_with_identity = (id) ->
      if !id
        $('.timeslot')
      else
        $('.timeslot').filter ->
          !!$(this).find(".identity[data-id='" + id + "']").length

app/views/schedules/_timeslot.html.haml
.timeslot{id: "timeslot_#{slot.id}", style: "background-color: #{lighten_color slot.category.color, 0.4}; border-color: ##{slot.category.color}"}
  .pull-right.actions
    .x-small
      = link_to slot, method: :delete, remote: true do
        %i.fa.fa-trash
  .timestamp
    = offset_to_time(slot.offset, "%I:%M %P")
  .category
    = link_to(slot.category.name, category_path(slot.category), class: 'text-primary') if slot.category
  .identities
    - slot.identities.each do |identity|
      = image_tag identity.image, style: 'width: 24px', class: 'identity', data: { toggle: 'tooltip', title: "#{identity.subname} - #{identity.provider}", id: identity.id}

app/views/schedules/add_timeslot.js.haml
var appearance = $("#{escape_javascript(render partial: 'schedules/timeslot', locals: { slot: @timeslot })}");
$("#schedule_#{@timeslot.schedule_id} #day_#{@timeslot.day}_block_#{@timeslot.offset / minutes_per_block}").append(appearance)
$("input[name='timeslot[offset]'").val('')
$(".add-timeslot-form").addClass('hidden')
$('.dialog-timeslot').modal('hide')
$("#dialog_timeslot_#{@timeslot.schedule_id}").modal('hide')

app/views/schedules/index.html.haml
.container
  .row
    .col-md-12
      %h1.page-title
        Your Social Media Schedules
      %h4.page-subtitle
        Choose when you want your updates to be sent. Octoforce will pull them from the selected category and send them out at the right time. And if you ever run out of updates, it will automatically reschedule your oldest ones. Now - get scheduling!
      %hr/
      = render partial: 'schedules/schedule', locals: { timeslots: @timeslots, identities: @identities }