config/routes.rb
require 'sidekiq/web'
require 'sidekiq/cron/web'

Rails.application.routes.draw do
  mount Sidekiq::Web, at: '/sidekiq'
  mount SuperfeedrEngine::Engine => SuperfeedrEngine::Engine.base_path # Use the same to set path in the engine initialization!

  namespace :admin do
    devise_scope :admin_user do
      get '/stats/:scope' => "stats#stats", as: :admin_stats
    end
  end

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users, class_name: 'FormUser', :controllers => { omniauth_callbacks: 'omniauth_callbacks', registrations: 'registrations', sessions: 'sessions', invitations: 'invitations' }, :skip => [:sessions]
  as :user do
    get 'login' => 'devise/sessions#new', :as => :new_user_session
    post 'login' => 'devise/sessions#create', :as => :user_session
    delete 'logout' => 'devise/sessions#destroy', :as => :destroy_user_session
  end
  root 'onboarding#check'
  get '/setup' => 'setup#index'

  get '/welcome' => 'onboarding#step1'
  get '/welcome/step0' => 'onboarding#step1'
  get '/welcome/step1' => 'onboarding#step1'
  get '/welcome/step1/done' => 'onboarding#step1_done'
  get '/welcome/step2' => 'onboarding#step2'
  get '/welcome/step3' => 'onboarding#step3'
  post '/welcome/step3/publish' => 'onboarding#step3_publish', as: 'onboarding_schedule_post'
  get '/welcome/step4' => 'onboarding#step4'
  get '/welcome/step5' => 'onboarding#step5'
  get '/welcome/step6' => 'onboarding#step6'

  resources :schedules, only: :index do
    post '/add_timeslot' => 'schedules#add_timeslot'
  end
  resources :categories do
    resources :posts, only: [:create]
    post 'reorder'
    get '/posts/bulk' => 'posts#show_bulk'
    post '/posts/preview' => 'posts#bulk_preview'
    post '/posts/bulk' => 'posts#create_bulk'
  end
  resources :feeds, only: [:index, :create, :update, :destroy]
  resources :identities, path: 'accounts'
  resources :posts, only: [:update, :edit, :destroy, :create]
  resources :timeslots, only: [:new, :create, :edit, :destroy]
  resources :assets, path: 'files', only: [:create, :destroy]

  get '/import/twitter' => 'import#twitter_setup'
  post '/import/twitter' => 'import#twitter'
  get '/import/twitter/:id' => 'import#show_twitter', as: 'import_show_twitter'
  post '/import' => 'import#import'
  get '/import/csv' => 'import#csv_setup'
  post '/import/csv' => 'import#csv_import'
  post '/import/csv/preview' => 'import#csv_preview'

  get '/library' => 'library#index'
  get '/add_content' => 'library#add_content', as: 'add_content'

  get '/queue' => 'queue#index'
  get '/queue/reschedule' => 'queue#reschedule'
  post '/queue/skip/:update_id' => 'queue#skip', as: 'skip_update'
  get '/analytics' => 'analytics#index'

  get '/:id' => "shortener/shortened_urls#show", constraints: { subdomain: 'shorten' }

  post '/ajax/scraper' => 'ajax#scraper'

end

app/models/update.rb
class Update < ActiveRecord::Base
  include Filterable
  include TwitterValidator
  has_shortened_urls
  belongs_to :user
  belongs_to :timeslot
  belongs_to :category, touch: true
  belongs_to :asset
  belongs_to :post, touch: true
  belongs_to :link
  belongs_to :identity, touch: true
  scope :scheduled, -> { where("scheduled_at > ?", Time.zone.now) }
  scope :published, -> pub = true { where("published = ?", pub) }
  scope :sorted, -> { order("scheduled_at ASC") }
  scope :time_ago, -> (field, time) { where("? >= ?", field.to_s, time)}
  scope :category, -> (category_ids) { where category_id: category_ids.split(',').flatten }
  scope :identity, -> (identity_ids) { where identity_id: identity_ids.split(',').flatten }

  def has_media?
    !asset.nil?
  end

  def media_url options = {}
    options = :original if options.empty?
    asset.media.url options
  end

  def unschedule
    post.move_to_front identity
    self.destroy
  end

  def category_color
    category ? category.color : '757575'
  end

  def social_media_url
    return nil if !published
    case self.identity.provider
    when Identity::FACEBOOK_PROFILE, Identity::FACEBOOK_GROUP, Identity::FACEBOOK_PAGE
      return "https://www.facebook.com/#{response_id}"
    when Identity::TWITTER
      return "https://twitter.com/octoforce/status/#{response_id}"
    when Identity::GITHUB
    when Identity::GOOGLE_PLUS
    when Identity::INSTAGRAM
    end
    return nil
  end

  def contains_provider? provider
    identity.provider == provider.to_s
  end

end

app/views/updates/_update.html.haml
/ # - cache ["v1", update, update.identity, update.category] do
%div{class: "#{update.category.name.gsub(' ','_').downcase}", id: "update_#{update.id}"}
  = render partial: 'shared/error_message', locals: { resource: update }
  .color-code{style: "background: #{lighten_color update.category.color, 0.15}"}
  .header.m15
    .profile
      %i{'class': "fa fa-#{update.identity.provider} bg-#{update.identity.provider}"}
      %img{'src': update.identity.image}
    .time-ago
      = timeago calculate_local_time(update.scheduled_at)
    .account
      %strong= update.identity.name
      %span.text-muted.text-light= update.identity.subname
    .timestamp.text-muted
      %i.fa.fa-clock-o
      = calculate_local_time(update.scheduled_at).strftime("%l:%M %P - %d/%m/%y")
  .body
    - if update.has_media?
      .pull-right{style: 'margin-left: 10px'}
        = link_to (image_tag update.media_url(:thumb)), update.media_url
    .text.large.m15
      = raw auto_link show update.text
    - if update.link
      .link-container.m10
        .row
          .col-md-3
            .thumb
              .image-container
                = image_tag update.link.image_url
          .col-md-9{style: 'padding: 10px 0'}
            %p.m5.small
              %strong= raw auto_link show update.link.title
            %p.m10.small.text-muted
              = update.link.description
            %p.m0.text-muted.x-small.text-uppercase
              = link_to update.link.caption, update.link.url, class: 'text-muted'
    .clearfix
  .footer
    .category-badge
      .name
        = update.category.name
    .pull-right.small.actions
      = link_to skip_update_path(update, @filtering_params), method: 'POST', class: 'text-muted action' do
        skip
        = " | "
        = link_to edit_post_path(update.post), data: { disable_with: 'loading...' }, class: 'text-muted action' do
          edit
    .clearfix