config/routes.rb
require 'sidekiq/web'
require 'sidekiq/cron/web'

Rails.application.routes.draw do
  mount Sidekiq::Web, at: '/sidekiq'
  mount SuperfeedrEngine::Engine => SuperfeedrEngine::Engine.base_path # Use the same to set path in the engine initialization!

  namespace :admin do
    devise_scope :admin_user do
      get '/stats/:scope' => "stats#stats", as: :admin_stats
    end
  end

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users, class_name: 'FormUser', :controllers => { omniauth_callbacks: 'omniauth_callbacks', registrations: 'registrations', sessions: 'sessions', invitations: 'invitations' }, :skip => [:sessions]
  as :user do
    get 'login' => 'devise/sessions#new', :as => :new_user_session
    post 'login' => 'devise/sessions#create', :as => :user_session
    delete 'logout' => 'devise/sessions#destroy', :as => :destroy_user_session
  end
  root 'onboarding#check'
  get '/setup' => 'setup#index'

  get '/welcome' => 'onboarding#step1'
  get '/welcome/step0' => 'onboarding#step1'
  get '/welcome/step1' => 'onboarding#step1'
  get '/welcome/step1/done' => 'onboarding#step1_done'
  get '/welcome/step2' => 'onboarding#step2'
  get '/welcome/step3' => 'onboarding#step3'
  post '/welcome/step3/publish' => 'onboarding#step3_publish', as: 'onboarding_schedule_post'
  get '/welcome/step4' => 'onboarding#step4'
  get '/welcome/step5' => 'onboarding#step5'
  get '/welcome/step6' => 'onboarding#step6'

  resources :schedules, only: :index do
    post '/add_timeslot' => 'schedules#add_timeslot'
  end
  resources :categories do
    resources :posts, only: [:create]
    post 'reorder'
    get '/posts/bulk' => 'posts#show_bulk'
    post '/posts/preview' => 'posts#bulk_preview'
    post '/posts/bulk' => 'posts#create_bulk'
  end
  resources :feeds, only: [:index, :create, :update, :destroy]
  resources :identities, path: 'accounts'
  resources :posts, only: [:update, :edit, :destroy, :create]
  resources :timeslots, only: [:new, :create, :edit, :destroy]
  resources :assets, path: 'files', only: [:create, :destroy]

  get '/import/twitter' => 'import#twitter_setup'
  post '/import/twitter' => 'import#twitter'
  get '/import/twitter/:id' => 'import#show_twitter', as: 'import_show_twitter'
  post '/import' => 'import#import'
  get '/import/csv' => 'import#csv_setup'
  post '/import/csv' => 'import#csv_import'
  post '/import/csv/preview' => 'import#csv_preview'

  get '/library' => 'library#index'
  get '/add_content' => 'library#add_content', as: 'add_content'

  get '/queue' => 'queue#index'
  get '/queue/reschedule' => 'queue#reschedule'
  post '/queue/skip/:update_id' => 'queue#skip', as: 'skip_update'
  get '/analytics' => 'analytics#index'

  get '/:id' => "shortener/shortened_urls#show", constraints: { subdomain: 'shorten' }

  post '/ajax/scraper' => 'ajax#scraper'

end

app/models/onboarding.rb
class Onboarding < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :identities, dependent: :destroy
  has_many :categories, dependent: :destroy
  has_many :timeslots, dependent: :destroy
  has_many :updates, dependent: :destroy
  has_many :posts, dependent: :destroy
  has_many :assets, dependent: :destroy
  has_many :feeds, dependent: :destroy
  has_many :csvs, dependent: :destroy
  after_create :setup_user
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :omniauthable, :invitable, :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable

  def tzinfo
    TZInfo::Timezone.get(timezone)
  end

  def bitly_client
    return nil if self.bitly_login.nil? || self.bitly_api_key.nil?
    @bitly_client ||= Bitly.new(self.bitly_login, self.bitly_api_key)
  end

  def providers
    identities.pluck(:provider).map { |name| name.split('_').first }.uniq
  end

  private

  def setup_user
    return unless self.categories.empty?
    self.categories.create name: "Blog Posts"
    self.categories.create name: "Quotes"
    self.categories.create name: "Promotion"
    self.categories.create name: "Curated Content"
    self.categories.create name: "Fun Stuff"
  end

end

app/controllers/onboarding_controller.rb
class OnboardingController < ApplicationController

  def check
    if current_user && current_user.onboarding_active && current_user.onboarding_step == 0
      redirect_to action: 'step1'
    else
      redirect_to queue_path
    end
  end

  def step1
    current_user.update onboarding_step: 1
    @identities = current_user.identities
  end

  def step2
    current_user.update onboarding_step: 2
    @posts = current_user.posts
    @post = Post.new
    current_user.identities.each { |identity| @post.social_media_posts.build identity: identity }
    @post.text = 'Testing this new rescheduling tool by @octoforce #socialmedia #automation #testing' if @posts.empty?
    @categories = current_user.categories
    c = current_user.categories.find_by name: 'twitter_import'
    @updates = c ? c.updates : [];
  end

  def step3
    current_user.update onboarding_step: 3
    @post = current_user.posts.last
    @timeslots = current_user.timeslots
    @categories = current_user.categories.includes(:posts)
    @identities = current_user.identities
    @slot = Timeslot.new
    if @identities.size == 1
      @slot.identity_ids = @identities.map &:id
    end
  end

  def step3_publish
    slot = Timeslot.create_with_timestamp timeslot_params.merge(user: current_user)
    SchedulingFacade.reschedule_category slot.category, 2
    redirect_to action: 'step4'
  end

  def step4
    current_user.update onboarding_step: 4
    # current_user.update onboarding_active: false
    @filtering_params = filtering_params
    @updates = current_user.updates.published(false).includes(:identity, :category).filter(@filtering_params).sorted
    @identities = current_user.identities.includes(:updates)
    @categories = current_user.categories.includes(:updates)
    @timeslot = current_user.timeslots.first
  end

  def step5
    current_user.update onboarding_step: 5
    @post = Post.new
    current_user.identities.each { |identity| @post.social_media_posts.build identity: identity }
  end

  def step6
    current_user.update onboarding_step: 6, onboarding_active: false
  end

  private

  def filtering_params
    params.slice(:category, :identity)
  end

  def timeslot_params
    params.require(:timeslot).permit(:schedule_id, :day, :offset, :category_id)
  end

end

app/helpers/onboarding_helper.rb
module OnboardingHelper
  include SchedulesHelper
  include QueueHelper
end

app/views/onboarding/_progress.html.haml
.progress.m5
  .progress-bar.progress-bar-success.progress-bar-striped{style: "width: #{amount}%;", role: 'progressbar', aria: { valuenow: amount, min: 0, max: 100}}
    = text

app/views/onboarding/step1.html.haml
- content_for :step_info, flush: true do
  .tips-header.bg-info
    .container
      .row
        .col-md-12
          .dialog
            = render partial: 'onboarding/progress', locals: { amount: 100/6, text: 'step 1 of 6'}
            %h1
              %strong Step 1:
              = t 'onboarding.step1.title'
            .actions.pull-right
            .description
              %p
                Octoforce is a social media scheduling tool with a focus on recycling your posts. In order to fully experience its awesomeness, you do need to connect at least one social media account.
              %p
                So let's do that first below!
            = link_to welcome_step2_path, class: 'small hidden-action' do
              I'll do this later
              %i.fa.fa-angle-right
.container
  .row
    .col-md-12
  .row
    .col-md-12
      %h1.page-title
        Social Media Accounts
      %h4.page-subtitle
        You currently have
        %strong
          = "#{@identities.count} account#{'s' if @identities.count != 1}"
        connected to Octoforce.
      %hr/
      - if @identities.size != 0
        .row
          - @identities.each do |identity|
            .col-md-4.col-sm-6.m30
              = render identity
          .col-md-12
            %h2.m20
              Connect more social platforms:

      .row
        .col-md-12.x-large.center.text-center.col-md-offset-2
          %i.fa.fa-4x.fa-twitter.color-twitter.m20
          = link_to 'connect your twitter account', omniauth_authorize_path('user', 'twitter', force_login: true), class: 'btn btn-twitter btn-lg'



- if current_user.email.nil?
  .modal.fade{tabindex: 1, role: 'dialog', 'data-show': 'true', 'data-toggle': 'modal', 'data-backdrop': 'static', 'data-keyboard': 'false'}
    .modal-dialog{style: 'max-width: 400px'}
      .modal-content
        .modal-header
          %h3.modal-title
            Complete your account
        .modal-body
          %p.large
            Enter the email address where we can best reach you.
          %p.m20
            We'll send you some tips about octoforce and warn you if anything goes wrong.
          = text_field_tag :email, nil, class: 'form-control m10', placeholder: 'enter email here', autofocus: 'autofocus'
          = submit_tag "Let's get started!", class: 'form-control btn btn-primary'

app/views/onboarding/step1_done.html.haml
- content_for :step_info do
  .tips-header.bg-info
    .container
      .row
        .col-md-12
          .dialog
            = render partial: 'onboarding/progress', locals: { amount: 100/6, text: 'step 1 of 6'}

            %h1
              %strong Step 1:
              %del Connect a Social Media Account
              %span.text-success
                DONE
            .description
              %p
                Alright - that looks great!
              %p
                If you want, you can add many more accounts. There is no limit right now.
            .bottom
              .pull-right
                = link_to welcome_step2_path, class: 'btn btn-primary' do
                  Go to Step 2: Adding your First Post
                  %i.fa.fa-angle-double-right
              %p
                I'm good for now. Let's post something!
              .clearfix
.container
  .row
    .col-md-12
  .row
    .col-md-10.col-md-offset-1
      %h1.page-title
        Social Media Accounts
      %h4.page-subtitle
        You currently have
        %strong
          = @identities.count
          accounts
        on Octoforce.
      %hr/
      .row
        - @identities.each do |identity|
          .col-md-4.col-sm-6.m20
            .card.bordered
              .profile-image
                %img.rounded{src: "#{identity.image}"}
              .next-to-image
                %strong= identity.subname || identity.name
                .text-muted.small= identity.provider
                %small= link_to 'remove', identity_path(identity), method: :delete, data: { confirm: 'This will also remove the connected schedule. Are you sure you want to proceed?' }
      %hr/


      = render partial: 'add'




- if current_user.email.nil?
  .modal.fade{tabindex: 1, role: 'dialog', 'data-show': 'true', 'data-toggle': 'modal', 'data-backdrop': 'static', 'data-keyboard': 'false'}
    .modal-dialog{style: 'max-width: 400px'}
      .modal-content
        .modal-header
          %h3.modal-title
            Complete your account
        .modal-body
          %p.large
            Enter the email address where we can best reach you.
          %p.m20
            We'll send you some tips about octoforce and warn you if anything goes wrong.
          = text_field_tag :email, nil, class: 'form-control m10', placeholder: 'enter email here', autofocus: 'autofocus'
          = submit_tag "Let's get started!", class: 'form-control btn btn-primary'

app/views/onboarding/step2.html.haml
- content_for :step_info do
  .tips-header.bg-info
    .container
      .row
        .col-md-12
          .dialog
            = render partial: 'onboarding/progress', locals: { amount: 200/6, text: 'step 2 of 6'}
            %h1
              %strong Step 2:
              = t 'onboarding.step2.title'
            .actions.pull-right
            .description
              %p
                What is a scheduling tool without content? Exactly, completely useless.
              %p
                In order to see what Octoforce can do, you need to write your very first post. Or copy-paste one of your previously written ones in here. After all, we are a very heavy cheerleader for recycling.
              %p.small
                Step 5 will introduce some other possibilities to get your existing content into Octoforce, but for now we will do it the old-school way: plain old typing.
            - if @posts.size > 0
              .bottom
                .pull-right
                  = link_to welcome_step3_path, class: 'btn btn-primary btn-lg' do
                    Go to Step 3:
                    = t 'onboarding.step3.title'
                    %i.fa.fa-angle-right
                %p
                  I've got enough posts in my library for now
                .clearfix

.container
  .row
    .col-md-12
      %h1.page-title
        Write Your Very First Posts
      %h4.page-subtitle
        To make it easy, I already provided you with a simple example. Feel free to use this or type out your own.
      .page-subtitle
        Don't worry, nothing will be scheduled. That's the next step.
      %hr/
      = render partial: 'posts/form', locals: { categories: @categories, select_category: true, post: @post, redirect: welcome_step3_path }

app/views/onboarding/step3.html.haml
- content_for :step_info do
  .tips-header.bg-info
    .container
      .row
        .col-md-12
          .dialog
            .progress
              .progress-bar.progress-bar-success.progress-bar-striped{style: 'width: 50%;', role: 'progressbar', aria: { valuenow: 50, min: 0, max: 100}}
                step 3 of 6
            %h1
              %strong Step 3:
              - if @timeslots.size == 0
                = t 'onboarding.step3.title'
              - else
                You can add as many timeslots as you want
            .actions.pull-right
            .description
              %p
                Octoforce automatically fills in your calendar based on your schedule. You do need to add some timeslots to your schedule to tell it what type of content you want scheduled when.
            - if @timeslots.size == 0
              = link_to welcome_step4_path, class: 'small hidden-action' do
                I'll do this later
                %i.fa.fa-angle-right
            - else
              .bottom
                .pull-right
                  = link_to welcome_step4_path, class: 'btn btn-primary btn-lg' do
                    Go to Step 4:
                    = t 'onboarding.step4.title'
                    %i.fa.fa-angle-right
                %p
                  I like the way my schedule looks right now
                .clearfix


.container
  .row
    .col-md-12
      %h1.page-title
        Fill in the Blanks
      %h4.page-subtitle
        Just select options from the dropdowns and I will add a matching timeslot in your calendar.
      %hr.m30/
    .col-md-8.col-md-offset-2
      = form_for @slot, html: {class: 'form-inline center m30'} do |f|
        = hidden_field_tag :redirect, request.path
        %p.m20
          %span.x-large{style: 'line-height: 40px'}
            Every
            = f.select :day, day_options, { prompt: 'select a day'}, class: 'form-control', prompt: 'select a day', required: 'required'
            at
            = f.time_field :offset, class: 'form-control', required: 'required'
            I want to publish one post from
            = f.select :category_id, category_options, {prompt: 'choose a category'}, class: 'form-control', required: 'required'
            to
          = f.select :identity_ids, identity_options, {include_hidden: false}, placeholder: 'select at least 1 account', class: 'form-control select-identities', multiple: true, required: 'required', style: 'width: 300px'
        = f.submit 'Update my Schedule', class: 'form-control btn btn-primary'
  .row
    .col-md-12
      %h1.page-title
        Or add timeslots directly to your schedule yourself
      %h4.page-subtitle
        Basically the same as above, but not as nicely formatted.
      %hr/
    .col-md-12
      = render partial: 'schedules/schedule', locals: { timeslots: @timeslots, identities: @identities }


- content_for :javascripts do
  :javascript
    $(function() {
      $('.select-identities').select2({
        placeholder: 'Select at least 1 account'
      });
    })

app/views/onboarding/step4.html.haml
- content_for :step_info do
  .tips-header.bg-info
    .container
      .row
        .col-md-12
          .dialog{style: 'margin-bottom: 0'}
            .progress
              .progress-bar.progress-bar-success.progress-bar-striped{style: 'width: 67%;', role: 'progressbar', aria: { valuenow: 67, min: 0, max: 100}}
                step 4 of 6
            %h1
              %strong Step 4:
              = t 'onboarding.step4.title'
            .actions.pull-right
            .description
              %p
                Below you can see your queue. This is a complete overview of all the posts Octoforce has scheduled to go out in the next 2 weeks.
              %p
                If you have only created 1 post in step 2, you may see it show up multiple times. That's because we believe in rescheduling your content. Adding more content to the same category will make sure you don't repeat yourself too often.
              %p
                The next step introduces 2 new possibilities that make it easier and faster to add content in bulk.
            .bottom
              .pull-right
                = link_to welcome_step5_path, class: 'btn btn-primary btn-lg' do
                  Go to Step 5:
                  = t 'onboarding.step5.title'
                  %i.fa.fa-angle-right
              %p
                Show me those new moves!
              .clearfix

.container
  = render partial: 'queue/queue', locals: { updates: @updates, categories: @categories, identities: @identities }

app/views/onboarding/step5.html.haml
- content_for :step_info, flush: true do
  .tips-header.bg-info
    .container
      .row
        .col-md-12
          .dialog
            = render partial: 'onboarding/progress', locals: { amount: 500/6, text: 'step 5 of 6'}
            %h1
              %strong Step 5:
              = t 'onboarding.step5.title'
            .actions.pull-right
            .description
              %p
                In order to make the most out of Octoforce, you really need to fill up your library.
              %p
                I know, it's not the most exciting part. But to make it easier, you can find 2 new options below on the right. Both of those can save you a lot of time getting set up.
              %p
                If you are already keeping track of tweets in a spreadsheet (Excel, Google Drive...), good on you! You can quickly import all of them using the 'Import a CSV file' button. Head on over there for more information.
              %p
                If you have been active on Twitter for a while & you have been sending out some quality tweets before, you can import those into Octoforce. Click the 'Import from Twitter' button and Octoforce will look up your previous tweets. You can then categorize them & add them all in one fell swoop.

            = link_to welcome_step6_path, class: 'small hidden-action' do
              I like my library the way it is right now
              %i.fa.fa-angle-right

= render partial: 'library/add_content', locals: { categories: current_user.categories, post: @post }

app/views/onboarding/step6.html.haml
- content_for :step_info do
  .tips-header.bg-info
    .container
      .row
        .col-md-12
          .dialog
            .progress
              .progress-bar.progress-bar-success.progress-bar-striped{style: 'width: 100%;', role: 'progressbar', aria: { valuenow: 100, min: 0, max: 100}}
                step 6 of 6 - DONE
            %h1
              %strong Step 6:
              = t 'onboarding.step6.title'
            .actions.pull-right
            .description
              %p
                %strong Congratulations are in order.
              %p
                You now know the basics of Octoforce & you are a huge step closer towards automating your social media presence.
                There are of course quite a few things that we did not touch on.
              %p
                Below I list a number of actions you may want to look into deeper. You can also just use the menu up top.
.container
  .row
    .col-md-12
  .row
    .col-md-12
      %h1.page-title
        Congratulations on completing this mini tour!
      %h4.page-subtitle
        Below are a number of links you may want to check out.
      %hr/
  .row
    .col-md-10.col-md-offset-1
      .m30
        %h2 Check out your Scheduling Calendar
        %p
          Add extra timeslots in
          = link_to "your scheduling calendar.", schedules_path
          You should probably post multiple times per day, but you can start out slower if your library is still small.
      .m30
        %h2 Using RSS Feeds
        %p
          If you have your own blog, you definitely want to
          = link_to 'add it to your feeds', feeds_path
          so that new posts automatically are added to your library. You can also add any other feeds you find interesting.
      .m30
        %h2 Adding more Social Media Accounts
        %p
          You can
          = link_to 'add extra social media profiles', identities_path
          (currently only Twitter, but Facebook & LinkedIn are coming).