config/routes.rb
require 'sidekiq/web'
require 'sidekiq/cron/web'

Rails.application.routes.draw do
  mount Sidekiq::Web, at: '/sidekiq'
  mount SuperfeedrEngine::Engine => SuperfeedrEngine::Engine.base_path # Use the same to set path in the engine initialization!

  namespace :admin do
    devise_scope :admin_user do
      get '/stats/:scope' => "stats#stats", as: :admin_stats
    end
  end

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users, class_name: 'FormUser', :controllers => { omniauth_callbacks: 'omniauth_callbacks', registrations: 'registrations', sessions: 'sessions', invitations: 'invitations' }, :skip => [:sessions]
  as :user do
    get 'login' => 'devise/sessions#new', :as => :new_user_session
    post 'login' => 'devise/sessions#create', :as => :user_session
    delete 'logout' => 'devise/sessions#destroy', :as => :destroy_user_session
  end
  root 'onboarding#check'
  get '/setup' => 'setup#index'

  get '/welcome' => 'onboarding#step1'
  get '/welcome/step0' => 'onboarding#step1'
  get '/welcome/step1' => 'onboarding#step1'
  get '/welcome/step1/done' => 'onboarding#step1_done'
  get '/welcome/step2' => 'onboarding#step2'
  get '/welcome/step3' => 'onboarding#step3'
  post '/welcome/step3/publish' => 'onboarding#step3_publish', as: 'onboarding_schedule_post'
  get '/welcome/step4' => 'onboarding#step4'
  get '/welcome/step5' => 'onboarding#step5'
  get '/welcome/step6' => 'onboarding#step6'

  resources :schedules, only: :index do
    post '/add_timeslot' => 'schedules#add_timeslot'
  end
  resources :categories do
    resources :posts, only: [:create]
    post 'reorder'
    get '/posts/bulk' => 'posts#show_bulk'
    post '/posts/preview' => 'posts#bulk_preview'
    post '/posts/bulk' => 'posts#create_bulk'
  end
  resources :feeds, only: [:index, :create, :update, :destroy]
  resources :identities, path: 'accounts'
  resources :posts, only: [:update, :edit, :destroy, :create]
  resources :timeslots, only: [:new, :create, :edit, :destroy]
  resources :assets, path: 'files', only: [:create, :destroy]

  get '/import/twitter' => 'import#twitter_setup'
  post '/import/twitter' => 'import#twitter'
  get '/import/twitter/:id' => 'import#show_twitter', as: 'import_show_twitter'
  post '/import' => 'import#import'
  get '/import/csv' => 'import#csv_setup'
  post '/import/csv' => 'import#csv_import'
  post '/import/csv/preview' => 'import#csv_preview'

  get '/library' => 'library#index'
  get '/add_content' => 'library#add_content', as: 'add_content'

  get '/queue' => 'queue#index'
  get '/queue/reschedule' => 'queue#reschedule'
  post '/queue/skip/:update_id' => 'queue#skip', as: 'skip_update'
  get '/analytics' => 'analytics#index'

  get '/:id' => "shortener/shortened_urls#show", constraints: { subdomain: 'shorten' }

  post '/ajax/scraper' => 'ajax#scraper'

end

app/models/category.rb
class Category < ActiveRecord::Base
  belongs_to :user
  has_many :posts, dependent: :destroy
  has_many :social_media_posts, through: :posts
  has_many :timeslots, dependent: :nullify
  has_many :updates, dependent: :nullify
  has_many :feeds, dependent: :destroy
  has_many :imported_updates, dependent: :destroy

  default_scope { order(name: :ASC) }

  after_initialize do |category|
    @generator = ColorGenerator.new saturation: 0.5, lightness: 0.5 unless @generator
    category.color ||= @generator.create_hex
  end

  def first_position
    first = social_media_posts.sorted.first
    first ? first.position || 100 : 100
  end

  def last_position
    social_media_posts.empty? ?
      100 :
      social_media_posts.sorted.last.position || 100
  end

  def find_next_post identity
    return nil unless identity
    social_media_posts.where('identity_id = ?', identity.id).sorted.first
  end

  def sorted_posts
    # always first show scheduled posts, based on scheduling time (should match position)
    # NB: we don't want to show posts with multiple scheduled updates ahead of the pack (reason for the weird zero? construction)
    posts.sort_by { |post| [post.updates.scheduled.count.zero? ? 0 : -1, post.position] }
  end

  def number_of_unique_days
    return 0 if updates.count == 0
    return -1 if timeslots.count == 0
    ((posts.count * 7)/ timeslots.count).to_i
  end

  def name_with_number
    "#{name} (#{posts.count})"
  end

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  load_and_authorize_resource

  def index
    @category = Category.new
    @posts = current_user.posts.filter(filtering_params)
  end

  def show
    @categories = current_user.categories.includes(:posts)
    @category = Category.find_by id: params[:id]
    @posts = @category.posts.sort_by { |p| [-p.updates.published(false).size, p.position] }
    @new_post = Post.new
    @new_category = Category.new
    authorize! :show, @category
  end

  def reorder
    category = Category.find_by id: params[:category_id]
    ids = params["ids"]
    if category && ids.size == category.posts.size
      # otherwise the category.reschedule will reset
      # the position of the posts which have scheduled updates.
      category.updates.scheduled.destroy_all
      ids.each_with_index do |id, i|
        p = Post.find_by id: id.to_i
        p.position = i + 1
        p.save
      end
      category.reschedule 2
    else
    end
    respond_to do |f|
      f.html { redirect_to category_path(category) }
      f.json do
        mapping = category.posts.map do |p|
          time = ''
          with_format :html do
            time = render_to_string partial: "categories/scheduling_time", locals: { post: p }
          end
          [p.id, time]
        end
        render json: mapping.to_h
      end
    end
  end

  def create
    category = Category.create category_params
    category.user = current_user
    if category.save
      intercom_event 'created-category', number_of_categories: current_user.categories.count
    end

    redirect_with_param library_path, notice: "Category '#{category.name}' has been created."
  end

  def destroy
    category = Category.find params["id"]
    name = category.name
    category.destroy
    redirect_to category_path(current_user.categories.first), notice: "Category '#{name}' has been removed"
  end

  private

  def category_params
    params.require(:category).permit(:name)
  end

  def post_params
    params.require(:post).permit(:category_id, :text, :asset)
  end

  def filtering_params
    params.slice(:category)
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper

  def identities
    current_user.identities
  end

  def calculate_category_amount category
    category.posts.size
  end

  def category_amount_tooltip
    "amount of posts in this category"
  end

end

app/views/categories/_category.html.haml
- category.posts.each do |post|
  .scheduled-update.m20{id: "post_#{post.id}"}
    = render partial: 'posts/post', locals: { post: post }

app/views/categories/_empty_library.html.haml
.row
  .col-md-8.col-md-offset-2
    .panel
      .panel-heading
        .panel-row
          .title
            %p
              This library is the core of your social media console.
          %div
            %p
              Start filling up this library with posts that you want your followers to see. You can get creative and carve your all-time best tweets or you can look at what posts have worked well in the past and copy them here so that new people can get to enjoy them.
            %p
              Octoforce will use this library to create a stream of content pulling posts one by one from your categories. Anything that is shared, is automatically added back to the end of the category so you never run out of things to say.
            %p
              So get started below by typing out your first post.

app/views/categories/_post.html.haml
- cache ["v2", post, post.asset] do
  .color-code{style: "background: #{lighten_color post.category_color, 0.15}"}
  .scheduling-time
    = render partial: "categories/scheduling_time", locals: { post: post }
  .body
    - if post.has_media?
      .pull-right.m10{style: 'margin-left: 10px'}
        = link_to (image_tag post.media_url(:thumb)), post.media_url
    .large.m10
      = raw auto_link show post.text
    .clearfix
  .footer
    - if !(preview ||= false)
      %span.pull-left.x-small
        = link_to 'move to top', '#', class: 'text-muted move-to-top', data: { target: target }
        = " | "
        = link_to 'move to bottom', '#', class: 'text-muted move-to-bottom', data: { target: target }
        = " | "
        = link_to "delete", post_path(post), { method: "delete", remote: true, class: 'text-muted' }
        = " | "
        = link_to 'edit', edit_post_path(post), remote: true, data: { disable_with: 'loading...' }, class: 'text-muted'
      .pull-right.x-small.text-muted
        %span
          added
          %abbr{title: "#{calculate_local_time(post.created_at).strftime("%l:%M %P - %d/%m/%y")}", data: {toggle: 'tooltip'}}
            = timeago post.created_at
      .clearfix

app/views/categories/_scheduling_time.html.haml
- if update = post.updates.published(false).first
  .x-small.text-muted.m5
    scheduled
    = timeago calculate_local_time(update.scheduled_at)
    for
    = "#{update.identity.subname} (#{update.identity.provider})"

app/views/categories/index.html.haml
.container
  .row
    .col-md-3
      .filter
        .title Categories
        %ul.categories
          - @categories.each do |category|
            = render partial: 'queue/category', locals: { category: category }
        = form_for Category.new, url: categories_path do |f|
          = f.text_field :name
          = f.submit "Create new category"

    .col-md-9
      .panel
        .panel-header
          .title
            Library
        .panel-body
          .category-posts
            - @posts.sorted.each do |post|
              .panel-row{id: "post_#{post.id}"}
                = render partial: 'posts/post', locals: { post: post }

app/views/categories/show.html.haml
.container
  .row
    .col-md-9.col-md-offset-3
      .actions.pull-right{style: 'margin-top: 20px'}
        = link_to 'delete', category_path(@category), data: {confirm: 'Are you sure you want to remove this category? This will also remove all posts in this category.'}, method: 'delete', class: 'btn btn-default'
      %h1.page-title
        = "Category '#{@category.name}'"
      %h4.page-subtitle
        Reorder posts by dragging them around. Scheduling times are recalculated behind the scenes and can take a little while to update.
      %hr/
  .row
    .col-md-3
      .filter
        .title Reorder another Category

        %ul.categories
          - @categories.each do |category|
            %li.category
              = link_to category_path(category), class: 'text-primary' do
                = render partial: 'shared/category', locals: { category: category }

    .col-md-9
      %div#sortable_list
        - @posts.each do |post|
          .draggable.scheduled-update.m20{id: "post_#{post.id}", data: { id: "#{post.id}" }}
            = render partial: 'categories/post', locals: { post: post, target: "#post_#{post.id}" }

- content_for :stylesheets do
  :css
    .sortable-ghost {
      border-width: 5px;
      border-style: dashed;
      position: relative;
    }
    .sortable-ghost:after {
      position: absolute;
      top: 0;
      right: 0;
      bottom: 0;
      left: 0;
      background: #fff;
      opacity: 0.9;
      content: '';
    }
    .draggable {
      cursor: move;
    }

- content_for :javascripts do
  :javascript
    Sortable.create(document.getElementById('sortable_list'), {
      draggable: '.draggable',
      ghostClass: 'sortable-ghost',
      chosenClass: 'sortable-chosen',
      onEnd: function(evt) {
        reorderPosts();
      }
    });
    $('.move-to-top').click(function(e) {
      e.preventDefault();
      target = $($(this).data('target'));
      target.siblings().first().before(target);
      reorderPosts();
    });
    $('.move-to-bottom').click(function(e) {
      e.preventDefault();
      target = $($(this).data('target'));
      target.siblings().last().after(target);
      reorderPosts();
    });
    var reorderPosts = function() {
      var ids = $('.scheduled-update').map(function() {
        return $(this).data('id');
      });
      $.post("#{category_reorder_path(@category)}", { ids: ids.toArray() }, function(data) {
        console.log(data);
        insertNewSchedulingTimes(data);
      }, 'json');
    };
    var insertNewSchedulingTimes = function(data) {
      $.each(data, function(key, value) {
        $("#post_" + key + " .scheduling-time").html(value);
      });
      $("time.timeago").timeago()
    };